"""
Test script for file system tools.
This tests the tools without requiring LLM API access.
"""

import json
from fs_tools import read_file, list_files, write_file, search_in_file


def print_result(title, result):
    """Pretty print test results."""
    print(f"\n{'='*60}")
    print(f"📋 {title}")
    print(f"{'='*60}")
    print(json.dumps(result, indent=2, default=str))


def test_list_files():
    """Test listing files in directory."""
    print("\n🧪 TEST 1: List all files in resumes folder")
    result = list_files("resumes")
    print_result("List All Files", result)
    
    print("\n🧪 TEST 2: List only TXT files")
    result = list_files("resumes", extension=".txt")
    print_result("List TXT Files", result)


def test_read_file():
    """Test reading files."""
    print("\n🧪 TEST 3: Read a text file")
    result = read_file("resumes/john_doe.txt")
    
    # Truncate content for display
    if result['success'] and len(result['content']) > 200:
        result['content'] = result['content'][:200] + "...[truncated]"
    
    print_result("Read File", result)


def test_search_in_file():
    """Test searching in files."""
    print("\n🧪 TEST 4: Search for 'Python' keyword")
    result = search_in_file("resumes/john_doe.txt", "Python")
    print_result("Search Results", result)


def test_write_file():
    """Test writing files."""
    print("\n🧪 TEST 5: Write a summary file")
    
    summary_content = """RESUME SUMMARY

Total resumes analyzed: 5

Candidates with Python experience:
- John Doe (5+ years, Python, JavaScript)
- Jane Smith (4 years, Python, R, Data Science)
- Sarah Williams (DevOps, Python scripting)

Candidates by role:
- Software Engineer: 1
- Data Scientist: 1
- Full Stack Developer: 1
- DevOps Engineer: 1
- Mobile Developer: 1

Generated by LLM File Assistant
"""
    
    result = write_file("outputs/summary.txt", summary_content)
    print_result("Write File", result)
    
    # Verify the file was written
    if result['success']:
        print("\n✅ Verifying file was created...")
        verify_result = read_file("outputs/summary.txt")
        if verify_result['success']:
            print(f"   ✓ File exists and is readable")
            print(f"   ✓ Size: {verify_result['metadata']['size_bytes']} bytes")


def test_error_handling():
    """Test error handling."""
    print("\n🧪 TEST 6: Error handling - nonexistent file")
    result = read_file("nonexistent/file.txt")
    print_result("Error Handling", result)


def main():
    """Run all tests."""
    print("🚀 Testing File System Tools")
    print("="*60)
    print("This script tests all fs_tools functions without LLM integration")
    
    try:
        test_list_files()
        test_read_file()
        test_search_in_file()
        test_write_file()
        test_error_handling()
        
        print("\n" + "="*60)
        print("✅ All tests completed!")
        print("="*60)
        
        print("\n💡 Next steps:")
        print("   1. Review test results above")
        print("   2. Set ANTHROPIC_API_KEY environment variable")
        print("   3. Run: python3 llm_file_assistant.py")
        print("   4. Try natural language queries!")
        
    except Exception as e:
        print(f"\n❌ Error during testing: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
